### ISSUE TITLE
Version Fix

### ISSUE THREAD

**Issue by ITEAmplify** [k1nky/netbox-scripthelper-plugin#6]
Hey, i made an Pull request #5 for updating the versions. I dont see any problems with netbox version 4.1.x

**Comment by k1nky** [comment]
Hi!

First of all, sorry for the long wait. The new release [v0.3.1](https://github.com/k1nky/netbox-scripthelper-plugin/releases/tag/v0.3.1) has been published. Thank you for your work and interest in the project.
